# Change these first
owner: Starlight-Community-Network # Your GitHub organization or username, where this repository lives
repo: Scumcraft-Status # The name of this repository
skipDeleteIssues: true
user-agent: upptime-bot

sites:
  - name: Scumcraft: Legacy
    check: "tcp-ping"
    url: legacy.scumcraft.starlightcommunity.net
    port: 25565
    icon: https://static.wixstatic.com/media/2d311a_ff5d4c5be50b4692a391da67869d1b95~mv2.png
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.scumcraft.starlightcommunity.net
  theme: night
  logoUrl: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  favicon: https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png
  name: Starlight Community Network
  introTitle: "**Welcome** to the Starlight Community Network Status Page."
  introMessage: When one of our Sites/Services Goes down you'll know here!
  metaTags:
    - name: "theme-color"
      content: "#874fbf" 
    - name: "og:site_name"
      content: "Starlight Community Network Powered By Upptime"
    - name: "og:type"
      content: "website" 
    - name: "og:title"
      content: "Starlight Community Network | Status"
    - name: "og:description"
      content: "Stay informed with real-time updates on our service status. Check for outages, scheduled maintenance, and performance metrics to ensure seamless connectivity."
    - name: "og:image"
      content: "https://static.wixstatic.com/media/af0f76_efa09e38ca6b4e30ad3616f0a632b1b6~mv2.png"
  navbar:
    - title: Status
      href: /
    - title: Status
      href: https://status.starlightcommunity.network
    - title: Main Site
      href: https://www.starlightcommunity.network
    - title: Fallback Site
      href: https://fallback.starlightcommunity.network
  robotsText: "User-agent: Googlebot \n Disallow: /"
